// web/src/components/UploadPanel.tsx
import { useState } from 'react'
import { List, Progress, Button, Space, Typography, Tooltip, Badge } from 'antd'
import {
    PauseCircleOutlined,
    PlayCircleOutlined,
    CloseOutlined,
    CopyOutlined,
    CheckCircleFilled,
    ExclamationCircleFilled,
    UpOutlined,
    DownOutlined,
    DeleteOutlined,
    CloudUploadOutlined,
} from '@ant-design/icons'
import { App } from 'antd'
import { useUploadStore } from '@/stores/uploadStore'
import { formatBytes, formatSpeed, copyToClipboard } from '@/utils/format'
import './UploadPanel.css'

const { Text } = Typography

export default function UploadPanel() {
    const { tasks, panelVisible, setPanelVisible, pauseTask, resumeTask, removeTask, clearCompleted } =
        useUploadStore()
    const [collapsed, setCollapsed] = useState(false)
    const { message } = App.useApp()

    if (!panelVisible || tasks.length === 0) return null

    const activeCount = tasks.filter((t) => t.status === 'uploading' || t.status === 'pending').length
    const completedCount = tasks.filter((t) => t.status === 'completed').length

    const handleCopy = async (text: string, label: string) => {
        await copyToClipboard(text)
        message.success(`${label} 已复制`)
    }

    return (
        <div className={`upload-panel ${collapsed ? 'collapsed' : ''}`}>
            <div className="upload-panel-header" onClick={() => setCollapsed(!collapsed)}>
                <Space>
                    <CloudUploadOutlined />
                    <Text strong>上传队列</Text>
                    {activeCount > 0 && (
                        <Badge count={activeCount} size="small" style={{ backgroundColor: '#1677ff' }} />
                    )}
                    {completedCount > 0 && (
                        <Badge count={`✓${completedCount}`} size="small" style={{ backgroundColor: '#52c41a' }} />
                    )}
                </Space>
                <Space>
                    {completedCount > 0 && (
                        <Button type="text" size="small" icon={<DeleteOutlined />} onClick={(e) => { e.stopPropagation(); clearCompleted() }}>
                            清理完成
                        </Button>
                    )}
                    <Button
                        type="text"
                        size="small"
                        icon={collapsed ? <UpOutlined /> : <DownOutlined />}
                    />
                    <Button
                        type="text"
                        size="small"
                        icon={<CloseOutlined />}
                        onClick={(e) => { e.stopPropagation(); setPanelVisible(false) }}
                    />
                </Space>
            </div>

            {!collapsed && (
                <div className="upload-panel-body">
                    <List
                        size="small"
                        dataSource={tasks}
                        renderItem={(task) => (
                            <List.Item className="upload-task-item">
                                <div className="upload-task-content">
                                    <div className="upload-task-row">
                                        <Text className="upload-filename" ellipsis={{ tooltip: task.filename }}>
                                            {task.filename}
                                        </Text>
                                        <Space size={4}>
                                            {task.status === 'uploading' && (
                                                <Text type="secondary" style={{ fontSize: 12 }}>
                                                    {formatSpeed(task.speed)}
                                                </Text>
                                            )}
                                            {task.status === 'uploading' && (
                                                <Tooltip title="暂停">
                                                    <Button type="text" size="small" icon={<PauseCircleOutlined />} onClick={() => pauseTask(task.id)} />
                                                </Tooltip>
                                            )}
                                            {task.status === 'paused' && (
                                                <Tooltip title="继续">
                                                    <Button type="text" size="small" icon={<PlayCircleOutlined />} onClick={() => resumeTask(task.id)} />
                                                </Tooltip>
                                            )}
                                            {task.status === 'completed' && (
                                                <>
                                                    <CheckCircleFilled style={{ color: '#52c41a' }} />
                                                    {task.url && (
                                                        <Tooltip title="复制直链">
                                                            <Button type="text" size="small" icon={<CopyOutlined />} onClick={() => handleCopy(task.url!, '直链')} />
                                                        </Tooltip>
                                                    )}
                                                    {task.markdown && (
                                                        <Tooltip title="复制 Markdown">
                                                            <Button type="text" size="small" onClick={() => handleCopy(task.markdown!, 'Markdown')}>
                                                                MD
                                                            </Button>
                                                        </Tooltip>
                                                    )}
                                                </>
                                            )}
                                            {task.status === 'failed' && (
                                                <Tooltip title={task.error || '上传失败'}>
                                                    <ExclamationCircleFilled style={{ color: '#ff4d4f' }} />
                                                </Tooltip>
                                            )}
                                            <Tooltip title="移除">
                                                <Button type="text" size="small" icon={<CloseOutlined />} onClick={() => removeTask(task.id)} />
                                            </Tooltip>
                                        </Space>
                                    </div>
                                    {(task.status === 'uploading' || task.status === 'paused') && (
                                        <Progress
                                            percent={task.progress}
                                            size="small"
                                            status={task.status === 'paused' ? 'exception' : 'active'}
                                            format={(p) => `${p}% · ${formatBytes(task.uploadedSize)} / ${formatBytes(task.totalSize)}`}
                                        />
                                    )}
                                </div>
                            </List.Item>
                        )}
                    />
                </div>
            )}
        </div>
    )
}

// image-web/src/components/UploadPanel.svelte
<script lang="ts">
  import { CheckCircle2, ChevronDown, ChevronUp, Pause, Play, RotateCcw, UploadCloud, X } from 'lucide-svelte'
  import { uploadQueue } from '../lib/upload-queue.svelte'
  import { formatBytes } from '../lib/utils'

  let collapsed = $state(false)
</script>

{#if uploadQueue.visible && uploadQueue.tasks.length > 0}
  <aside class:collapsed class="upload-panel" aria-label="上传队列">
    <header>
      <div class="upload-title">
        <UploadCloud size={17} />
        <strong>上传队列</strong>
        <span>{uploadQueue.pendingCount ? `${uploadQueue.pendingCount} 项进行中` : '全部完成'}</span>
      </div>
      <div class="icon-row">
        {#if uploadQueue.tasks.some((task) => task.status === 'completed')}
          <button class="icon-button" title="清除已完成" onclick={() => uploadQueue.clearCompleted()}><CheckCircle2 size={17} /></button>
        {/if}
        <button class="icon-button" title={collapsed ? '展开队列' : '收起队列'} onclick={() => collapsed = !collapsed}>
          {#if collapsed}<ChevronUp size={17} />{:else}<ChevronDown size={17} />{/if}
        </button>
      </div>
    </header>

    {#if !collapsed}<div class="upload-list">
      {#each uploadQueue.tasks as task (task.localId)}
        <article class="upload-item">
          <div class="upload-file">
            <strong title={task.filename}>{task.filename}</strong>
            <span>
              {#if task.status === 'completed'}已完成
              {:else if task.status === 'failed'}{task.error || '上传失败'}
              {:else if task.status === 'paused'}已暂停 · {formatBytes(task.uploadedSize)} / {formatBytes(task.totalSize)}
              {:else}{task.progress}% · {formatBytes(task.speed)}/s{/if}
            </span>
          </div>
          <div class="upload-actions">
            {#if task.status === 'uploading' || task.status === 'pending'}
              <button class="icon-button" title="暂停" onclick={() => uploadQueue.pause(task.localId)}><Pause size={16} /></button>
            {:else if task.status === 'paused'}
              <button class="icon-button" title="继续" onclick={() => uploadQueue.resume(task.localId)}><Play size={16} /></button>
            {:else if task.status === 'failed'}
              <button class="icon-button" title="重试" onclick={() => uploadQueue.resume(task.localId)}><RotateCcw size={16} /></button>
            {/if}
            <button class="icon-button" title="移除任务" onclick={() => uploadQueue.remove(task.localId)}><X size={16} /></button>
          </div>
          <div class="progress-track" aria-label={`上传进度 ${task.progress}%`}>
            <span class:failed={task.status === 'failed'} style={`width:${task.progress}%`}></span>
          </div>
        </article>
      {/each}
    </div>{/if}
  </aside>
{/if}
